### ISSUE TITLE
Make add-on OSGi compatible?

### ISSUE THREAD

**Issue by alexweirig** [basakpie/vaadin-onoffswitch-addon#5]
Hello,

do you plan to make your add-on OSGi compatible, i.e. generate a full OSGi MANIFEST.MF file with the required Import-Packages and Export-Packages statements?

Vaadin is making great efforts to finally support OSGi and it's a shame if the add-ons can't be (easily) used in OSGi.

BTW: if you need somebody to test, please let me know.

Many thanks in advance,

Alex

**Comment by alexweirig** [comment]
Hello,

this is the MANIFEST.MF when I use BND to convert your non-bundle into a valid bundle.

This should be enough to make it a valid OSGi bundle.

Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Bnd-LastModified: 1499428065225
Build-Jdk: 1.8.0_111
Built-By: gmind
Bundle-ManifestVersion: 2
Bundle-Name: OnOffSwitch
Bundle-SymbolicName: OnOffSwitch
Bundle-Version: 0
Class-Path: vaadin-server-8.0.6.jar vaadin-sass-compiler-0.9.13.jar sa
 c-1.3.jar flute-1.3.0.gg2.jar vaadin-shared-8.0.6.jar jsoup-1.8.3.jar
  gentyref-1.2.0.jar
Created-By: 1.8.0_131 (Oracle Corporation)
Export-Package: com.vaadin.addon.onoffswitch;uses:="com.vaadin.addon.o
 noffswitch.client,com.vaadin.shared,com.vaadin.shared.communication,c
 om.vaadin.ui",com.vaadin.addon.onoffswitch.client;uses:="com.google.g
 wt.event.logical.shared,com.google.gwt.event.shared,com.google.gwt.us
 er.client.ui,com.vaadin.addon.onoffswitch,com.vaadin.client.communica
 tion,com.vaadin.client.ui,com.vaadin.shared,com.vaadin.shared.communi
 cation,com.vaadin.shared.ui",com.vaadin.addon.onoffswitch.public.onof
 fswitch
Implementation-Title: OnOffSwitch
Implementation-Vendor-Id: com.vaadin.addon
Implementation-Version: 1.0.0
Import-Package: com.google.gwt.dom.client;resolution:=optional,com.goo
 gle.gwt.event.dom.client;resolution:=optional,com.google.gwt.event.lo
 gical.shared;resolution:=optional,com.google.gwt.event.shared;resolut
 ion:=optional,com.google.gwt.user.client;resolution:=optional,com.goo
 gle.gwt.user.client.ui;resolution:=optional,com.vaadin.addon.onoffswi
 tch;resolution:=optional,com.vaadin.addon.onoffswitch.client;resoluti
 on:=optional,com.vaadin.client;resolution:=optional,com.vaadin.client
 .communication;resolution:=optional,com.vaadin.client.ui;resolution:=
 optional,com.vaadin.shared;resolution:=optional,com.vaadin.shared.com
 munication;resolution:=optional,com.vaadin.shared.ui;resolution:=opti
 onal,com.vaadin.ui;resolution:=optional
Originally-Created-By: Apache Maven
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-3.3.0.201609221906
Vaadin-License-Title: Apache License 2.0
Vaadin-Package-Version: 1
Vaadin-Widgetsets: com.vaadin.addon.onoffswitch.WidgetSet

**Comment by alexweirig** [comment]
Hello,

to simplify the process, here's what you need to add to your pom.xml to make maven generate a valid MANIFEST.MF:

			  <plugin>
			    <groupId>biz.aQute.bnd</groupId>
			    <artifactId>bnd-maven-plugin</artifactId>
				<version>2.4.1</version>

				<executions>
					<execution>
						<goals>
							<goal>bnd-process</goal>
						</goals>
					</execution>
				</executions>
			  </plugin>

			  <plugin>
			      <groupId>org.apache.maven.plugins</groupId>
			      <artifactId>maven-jar-plugin</artifactId>
			      <configuration>
			          <archive>
			              <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
			          </archive>
			      </configuration>
			  </plugin>

I've tested this and it seems to work ... I hope there was no side-affect from my other tests.

Maybe you could run a build on your side and I could easily test this.

Kind regards,

Alex

**Comment by basakpie** [comment]
OSGI support. thank you.
