### ISSUE TITLE
The onValueChangeListener should set userOriginated to true when clicked

### ISSUE THREAD

**Issue by neerup** [basakpie/vaadin-onoffswitch-addon#7]
public void clicked(boolean checked) {
		    if (isReadOnly()) {
	                return;
	            }
	            final Boolean oldValue = getValue(); // 서버 value
	            final Boolean newValue = checked;    // 클라이언트측 요청 Value
	            // 양쪽 Value가 틀린 경우 Click 상태 값 변경 
	            if (!newValue.equals(oldValue)) {
	            	// 서버측 Value 변경
	                setValue(newValue, **Boolean.TRUE**);
	            }
	            // 클라이언트 RPC alert 메서드 호출
	            getRpcProxy(OnOffSwitchClientRpc.class).alert(String.valueOf(newValue));
	    };

**Comment by basakpie** [comment]
Change the state by comparing the client value with the server value.

**Comment by neerup** [comment]
How would I go about doing that ?

**Comment by basakpie** [comment]
OnOffSwitchClientRpc.class is an unnecessary task as an example(CHAPTER.15 My Add-ons) source discussed to explain the client side RPC functionality to the reader while writing the Vaadin related book([link](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&barcode=9791187497059
)) directly.
I am so sorry. I was mistaken. I will modify the source again to reflect it.
